# Generated by Django 3.1.2 on 2020-10-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
