# Generated by Django 3.1.2 on 2020-10-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201024_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
